### ISSUE TITLE
Improve MSBuild integration?

### ISSUE THREAD

**Issue by D0tNet4Fun** [vslavik/nuget-tools-innosetup#12]
This package is just what I needed for my project. Thank you for doing this!

I would like to contribute to this work by improving the integrating with MSBuild. I have this use case in my mind:
1. Create a new project that includes one or more ISS files.
2. Add this NuGet package to the project.
3. Build the project.

The package would replace the default `Build` target with a custom target whose job is to run the Inno Setup Compiler with parameters already defined in the project, i.e. the output file name is `$(MSBuildProjectName)`, the output directory is `$(OutDir)` etc. Also, the `Clean` target would delete the output file. These are IMO the first steps to turn a MSBuild project into a project that is aware of Inno Setup.

Please let me know if you think this would be a worthy addition to the package, or that it goes beyond its purpose. Thank you.

**Comment by vslavik** [comment]
This makes no sense to me.
