### ISSUE TITLE
Consider making available as dotnet tool

### ISSUE THREAD

**Issue by CoenraadS** [vslavik/nuget-tools-innosetup#13]
Hi, this project is a really useful initiative 

However I think it would also be great to be available via `dotnet tool install` command. Then I could install it via CLI without having to involve nuget restore.

A nice to have would be `ToolCommandName` invokes `ISCC.exe` somehow

**Comment by vslavik** [comment]
> However I think it would also be great to be available via dotnet tool install command.

I'm happy to merge a PR that you submit.
