### ISSUE TITLE
Nuspec mismatch

### ISSUE THREAD

**Issue by ZenoArrow** [vslavik/nuget-tools-innosetup#4]
Hi,

This issue may just be raised due to me misunderstanding how NuGet works, but it seems that the Tools.InnoSetup NuSpec file listed in GitHub (for version 5.6.1) doesn't match the NuSpec file found in Tools.InnoSetup 5.6.1 in the NuGet Gallery ( https://www.nuget.org/packages/Tools.InnoSetup/5.6.1 ).

In particular, the "files" section seems to be missing in the NuGet Gallery version:

    <files>
        <file src="license.txt" target="" />
        <file src="readme.txt" target="" />

        <file src="c:\Program Files (x86)\Inno Setup 5\Default.isl" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\isbunzip.dll" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\isbzip.dll" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\ISCC.exe" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\ISCmplr.dll" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\ISCrypt.dll" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\islzma.dll" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\islzma32.exe" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\islzma64.exe" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\ISPP.dll" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\ISPPBuiltins.iss" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\isscint.dll" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\isunzlib.dll" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\iszlib.dll" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\Languages\*.isl" target="tools\Languages" />
        <file src="c:\Program Files (x86)\Inno Setup 5\Languages\*.islu" target="tools\Languages" />
        <file src="c:\Program Files (x86)\Inno Setup 5\Setup.e32" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\SetupLdr.e32" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\WizModernImage-IS.bmp" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\WizModernImage.bmp" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\WizModernSmallImage-IS.bmp" target="tools" />
        <file src="c:\Program Files (x86)\Inno Setup 5\WizModernSmallImage.bmp" target="tools" />
</files>

Is there a reason for this?

Thanks in advance.

**Comment by vslavik** [comment]
Given that the page you link does even show the spec file and the built nuget's content matches what it was built from, yes, you seem to be confused.

**Comment by ZenoArrow** [comment]
Sorry, but I think you've misunderstood. The NuSpec is available from NuGet Gallery. All you have to do is download the .nupkg file and unzip it. The NuSpec file contained within this package does not match the one listed in this GitHub repository.

**Comment by ZenoArrow** [comment]
To save you the effort, this is what I'm seeing in the NuGet Gallery version...

![image](https://user-images.githubusercontent.com/1449002/48140159-1c2a9e80-e2a0-11e8-9711-86e1bef8bfd4.png)

This doesn't match the file contents listed here:

https://github.com/vslavik/nuget-tools-innosetup/blob/master/Tools.InnoSetup.nuspec

**Comment by vslavik** [comment]
It of course does, because it was built from it.

Before you make serious accusations like this, I suggest you first make at least a minimal effort to check your facts and establish your competency. In fact, before you decide to digging in binary files you should have some idea what you're doing. You also don't have to be an expert to behave reasonably and e.g. check a few unrelated packages before making accusations (as you do by claiming there's a mismatch between the binary I publish and the source).

You said it yourself:

> due to me misunderstanding how NuGet works

You didn't take a hint, so let me spell it out: the only issue is indeed on your end. Your expectation that *build instructions* would be included in a compiled package does not match how NuGet works.
